### PR TITLE
Adding an issue template

### PR DESCRIPTION
**Pull request by markjacksonfishing**
A very simple issue template we can iterate on if needed.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
What is the goal of this template?

**Comment by oleg-nenashev** [comment]
If this is for reviews, maybe it should follow the existing pattern, more or less

**Comment by markjacksonfishing** [comment]
Disregard me, this was for something else. I think I need a nap 🛌

**Comment by oleg-nenashev** [comment]
nws, thanks!

**Pull request closed without merging**
